// Roam wire protocol types and utilities

export {
  RpcError,
  RpcErrorCode,
  decodeUserError,
} from "./rpc_error.ts";

export type {
  Parity,
  ConnectionSettings,
  Hello,
  HelloYourself,
  ProtocolError,
  MetadataValueString,
  MetadataValueBytes,
  MetadataValueU64,
  MetadataValue,
  MetadataFlagsRepr,
  MetadataEntry,
  Metadata,
  ConnectionOpen,
  ConnectionAccept,
  ConnectionReject,
  ConnectionClose,
  RequestCall,
  RequestResponse,
  RequestCancel,
  RequestBody,
  RequestMessage,
  ChannelItem,
  ChannelClose,
  ChannelReset,
  ChannelGrantCredit,
  ChannelBody,
  ChannelMessage,
  MessagePayload,
  Message,
  MessageHello,
  MessageHelloYourself,
  MessageProtocolError,
  MessageConnect,
  MessageAccept,
  MessageReject,
  MessageGoodbye,
  MessageRequest,
  MessageResponse,
  MessageCancel,
  MessageData,
  MessageClose,
  MessageReset,
  MessageCredit,
  HelloV4,
  HelloV5,
  HelloV6,
} from "./types.ts";

export {
  MessageDiscriminant,
  MetadataValueDiscriminant,
  ParityDiscriminant,
  HelloDiscriminant,
  MetadataFlags,
  parityOdd,
  parityEven,
  connectionSettings,
  helloV7,
  helloYourself,
  helloV4,
  helloV5,
  helloV6,
  metadataString,
  metadataBytes,
  metadataU64,
  metadataEntry,
  messageHello,
  messageHelloYourself,
  messageProtocolError,
  messageConnect,
  messageAccept,
  messageReject,
  messageGoodbye,
  messageRequest,
  messageResponse,
  messageCancel,
  messageData,
  messageClose,
  messageReset,
  messageCredit,
} from "./types.ts";

export {
  ParitySchema,
  ConnectionSettingsSchema,
  HelloSchema,
  HelloYourselfSchema,
  ProtocolErrorSchema,
  MetadataValueSchema,
  MetadataEntrySchema,
  RequestBodySchema,
  RequestMessageSchema,
  ChannelBodySchema,
  ChannelMessageSchema,
  MessagePayloadSchema,
  MessageSchema,
  wireSchemaRegistry,
  getHelloSchema,
  getMetadataValueSchema,
  getMetadataEntrySchema,
  getMessageSchema,
} from "./schemas.ts";

export {
  encodeHello,
  decodeHello,
  encodeMetadataValue,
  decodeMetadataValue,
  encodeMetadataEntry,
  decodeMetadataEntry,
  encodeMessage,
  decodeMessage,
  encodeMessages,
  decodeMessages,
} from "./codec.ts";
